// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AIAutomationRunPublic
 */
export type AIAutomationRunPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Trigger
     */
    trigger: 'manual' | 'scheduled';
    /**
     * Status
     */
    status: 'running' | 'succeeded' | 'failed';
    /**
     * Scheduled For
     */
    scheduled_for: string;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Briefing Id
     */
    briefing_id: string | null;
    /**
     * Error
     */
    error: string | null;
};

/**
 * AIDailyAutomationPublic
 */
export type AIDailyAutomationPublic = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Run Time
     */
    run_time: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Next Run At
     */
    next_run_at: string | null;
    last_run: AIAutomationRunPublic | null;
};

/**
 * AIDailyAutomationUpdate
 */
export type AIDailyAutomationUpdate = {
    /**
     * Enabled
     */
    enabled?: boolean | null;
    /**
     * Run Time
     */
    run_time?: string | null;
};

/**
 * AIDailyBriefingPublic
 */
export type AIDailyBriefingPublic = {
    /**
     * Headline
     */
    headline: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Priorities
     */
    priorities: Array<string>;
    /**
     * Risks
     */
    risks: Array<string>;
    /**
     * Opportunities
     */
    opportunities: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Model
     */
    model: string;
    /**
     * Generation Mode
     */
    generation_mode: 'manual' | 'automation';
    source: DashboardSummaryPublic;
    /**
     * Generated By Id
     */
    generated_by_id: string | null;
};

/**
 * AIDailyBriefingsPublic
 */
export type AIDailyBriefingsPublic = {
    /**
     * Data
     */
    data: Array<AIDailyBriefingPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AIStatusPublic
 */
export type AIStatusPublic = {
    /**
     * Provider
     */
    provider?: 'ollama';
    /**
     * Status
     */
    status: 'ready' | 'unavailable' | 'model_missing';
    /**
     * Model
     */
    model: string;
    /**
     * Available Models
     */
    available_models: Array<string>;
    /**
     * Message
     */
    message: string;
};

/**
 * AIWeeklyReviewPublic
 */
export type AIWeeklyReviewPublic = {
    /**
     * Headline
     */
    headline: string;
    /**
     * Summary
     */
    summary: string;
    /**
     * Wins
     */
    wins: Array<string>;
    /**
     * Concerns
     */
    concerns: Array<string>;
    /**
     * Priorities
     */
    priorities: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Period Start Date
     */
    period_start_date: string;
    /**
     * Period End Date
     */
    period_end_date: string;
    /**
     * Generated At
     */
    generated_at: string;
    /**
     * Model
     */
    model: string;
    source: DashboardTrendsPublic;
    /**
     * Generated By Id
     */
    generated_by_id: string | null;
};

/**
 * AIWeeklyReviewsPublic
 */
export type AIWeeklyReviewsPublic = {
    /**
     * Data
     */
    data: Array<AIWeeklyReviewPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ActionItemCreate
 */
export type ActionItemCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category
     */
    category?: 'priority' | 'risk' | 'opportunity';
    /**
     * Priority
     */
    priority?: 'low' | 'medium' | 'high';
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Source Briefing Id
     */
    source_briefing_id?: string | null;
    /**
     * Source Weekly Review Id
     */
    source_weekly_review_id?: string | null;
    /**
     * Source Suggestion
     */
    source_suggestion?: string | null;
};

/**
 * ActionItemPublic
 */
export type ActionItemPublic = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category
     */
    category: 'priority' | 'risk' | 'opportunity';
    /**
     * Priority
     */
    priority: 'low' | 'medium' | 'high';
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: 'open' | 'in_progress' | 'completed' | 'dismissed';
    /**
     * Source Briefing Id
     */
    source_briefing_id: string | null;
    /**
     * Source Weekly Review Id
     */
    source_weekly_review_id: string | null;
    /**
     * Source Suggestion
     */
    source_suggestion: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Completed At
     */
    completed_at: string | null;
    /**
     * Outcome Note
     */
    outcome_note: string | null;
};

/**
 * ActionItemUpdate
 */
export type ActionItemUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Category
     */
    category?: 'priority' | 'risk' | 'opportunity' | null;
    /**
     * Priority
     */
    priority?: 'low' | 'medium' | 'high' | null;
    /**
     * Status
     */
    status?: 'open' | 'in_progress' | 'completed' | 'dismissed' | null;
    /**
     * Due Date
     */
    due_date?: string | null;
    /**
     * Outcome Note
     */
    outcome_note?: string | null;
};

/**
 * ActionItemsPublic
 */
export type ActionItemsPublic = {
    /**
     * Data
     */
    data: Array<ActionItemPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DashboardSummaryPublic
 */
export type DashboardSummaryPublic = {
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Revenue
     */
    revenue: string;
    /**
     * Sales Count
     */
    sales_count: number;
    /**
     * Units Sold
     */
    units_sold: string;
    /**
     * Average Sale Value
     */
    average_sale_value: string;
    /**
     * Top Products
     */
    top_products: Array<DashboardTopProductPublic>;
    /**
     * Low Stock Count
     */
    low_stock_count: number;
    /**
     * Low Stock
     */
    low_stock: Array<InventoryBalancePublic>;
};

/**
 * DashboardTopProductPublic
 */
export type DashboardTopProductPublic = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Quantity Sold
     */
    quantity_sold: string;
    /**
     * Revenue
     */
    revenue: string;
};

/**
 * DashboardTrendComparisonPublic
 */
export type DashboardTrendComparisonPublic = {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Revenue
     */
    revenue: string;
    /**
     * Sales Count
     */
    sales_count: number;
    /**
     * Units Sold
     */
    units_sold: string;
    /**
     * Revenue Change Percent
     */
    revenue_change_percent: string | null;
    /**
     * Sales Count Change Percent
     */
    sales_count_change_percent: string | null;
    /**
     * Units Sold Change Percent
     */
    units_sold_change_percent: string | null;
};

/**
 * DashboardTrendDayPublic
 */
export type DashboardTrendDayPublic = {
    /**
     * Report Date
     */
    report_date: string;
    /**
     * Revenue
     */
    revenue: string;
    /**
     * Sales Count
     */
    sales_count: number;
    /**
     * Units Sold
     */
    units_sold: string;
    /**
     * Average Sale Value
     */
    average_sale_value: string;
};

/**
 * DashboardTrendsPublic
 */
export type DashboardTrendsPublic = {
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Timezone
     */
    timezone: string;
    /**
     * Days
     */
    days: number;
    /**
     * Revenue
     */
    revenue: string;
    /**
     * Sales Count
     */
    sales_count: number;
    /**
     * Units Sold
     */
    units_sold: string;
    /**
     * Average Sale Value
     */
    average_sale_value: string;
    previous_period: DashboardTrendComparisonPublic;
    /**
     * Daily
     */
    daily: Array<DashboardTrendDayPublic>;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InventoryBalancePublic
 */
export type InventoryBalancePublic = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Product Name
     */
    product_name: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Is Active
     */
    is_active: boolean;
    /**
     * Track Inventory
     */
    track_inventory: boolean;
    /**
     * Reorder Level
     */
    reorder_level: string;
    /**
     * Quantity On Hand
     */
    quantity_on_hand: string;
    /**
     * Is Low Stock
     */
    is_low_stock: boolean;
};

/**
 * InventoryBalancesPublic
 */
export type InventoryBalancesPublic = {
    /**
     * Data
     */
    data: Array<InventoryBalancePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * InventoryMovementCreate
 */
export type InventoryMovementCreate = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Movement Type
     */
    movement_type: 'opening' | 'receipt' | 'adjustment';
    /**
     * Quantity Delta
     */
    quantity_delta: number | string;
    /**
     * Occurred At
     */
    occurred_at?: string;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * InventoryMovementPublic
 */
export type InventoryMovementPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Sale Id
     */
    sale_id: string | null;
    /**
     * Movement Type
     */
    movement_type: string;
    /**
     * Quantity Delta
     */
    quantity_delta: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * InventoryMovementsPublic
 */
export type InventoryMovementsPublic = {
    /**
     * Data
     */
    data: Array<InventoryMovementPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Selling Price
     */
    selling_price: number | string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Track Inventory
     */
    track_inventory?: boolean;
    /**
     * Reorder Level
     */
    reorder_level?: number | string;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Category
     */
    category: string;
    /**
     * Selling Price
     */
    selling_price: string;
    /**
     * Unit
     */
    unit: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Track Inventory
     */
    track_inventory?: boolean;
    /**
     * Reorder Level
     */
    reorder_level?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ProductUpdate
 */
export type ProductUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Category
     */
    category?: string | null;
    /**
     * Selling Price
     */
    selling_price?: number | string | null;
    /**
     * Unit
     */
    unit?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Track Inventory
     */
    track_inventory?: boolean | null;
    /**
     * Reorder Level
     */
    reorder_level?: number | string | null;
};

/**
 * ProductsPublic
 */
export type ProductsPublic = {
    /**
     * Data
     */
    data: Array<ProductPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SaleCreate
 */
export type SaleCreate = {
    /**
     * Sold At
     */
    sold_at?: string;
    /**
     * Items
     */
    items: Array<SaleItemCreate>;
};

/**
 * SaleItemCreate
 */
export type SaleItemCreate = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Quantity
     */
    quantity: number | string;
};

/**
 * SaleItemPublic
 */
export type SaleItemPublic = {
    /**
     * Product Id
     */
    product_id: string;
    /**
     * Quantity
     */
    quantity: string;
    /**
     * Unit Price
     */
    unit_price: string;
    /**
     * Line Total
     */
    line_total: string;
    /**
     * Id
     */
    id: string;
    /**
     * Sale Id
     */
    sale_id: string;
};

/**
 * SalePublic
 */
export type SalePublic = {
    /**
     * Sold At
     */
    sold_at?: string;
    /**
     * Total Amount
     */
    total_amount: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Items
     */
    items: Array<SaleItemPublic>;
};

/**
 * SalesPublic
 */
export type SalesPublic = {
    /**
     * Data
     */
    data: Array<SalePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * TrendDays
 */
export type TrendDays = 7 | 14 | 30;

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type actionsReadActionsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Status
         */
        status?: 'open' | 'in_progress' | 'completed' | 'dismissed' | null;
        /**
         * Category
         */
        category?: 'priority' | 'risk' | 'opportunity' | null;
        /**
         * Source Briefing Id
         */
        source_briefing_id?: string | null;
        /**
         * Source Weekly Review Id
         */
        source_weekly_review_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/actions/';
};

export type actionsReadActionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsReadActionsError = actionsReadActionsErrors[keyof actionsReadActionsErrors];

export type actionsReadActionsResponses = {
    /**
     * Successful Response
     */
    200: ActionItemsPublic;
};

export type actionsReadActionsResponse = actionsReadActionsResponses[keyof actionsReadActionsResponses];

export type actionsCreateActionData = {
    body: ActionItemCreate;
    path?: never;
    query?: never;
    url: '/api/v1/actions/';
};

export type actionsCreateActionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsCreateActionError = actionsCreateActionErrors[keyof actionsCreateActionErrors];

export type actionsCreateActionResponses = {
    /**
     * Successful Response
     */
    201: ActionItemPublic;
};

export type actionsCreateActionResponse = actionsCreateActionResponses[keyof actionsCreateActionResponses];

export type actionsDeleteActionData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/v1/actions/{action_id}';
};

export type actionsDeleteActionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsDeleteActionError = actionsDeleteActionErrors[keyof actionsDeleteActionErrors];

export type actionsDeleteActionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type actionsDeleteActionResponse = actionsDeleteActionResponses[keyof actionsDeleteActionResponses];

export type actionsReadActionData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/v1/actions/{action_id}';
};

export type actionsReadActionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsReadActionError = actionsReadActionErrors[keyof actionsReadActionErrors];

export type actionsReadActionResponses = {
    /**
     * Successful Response
     */
    200: ActionItemPublic;
};

export type actionsReadActionResponse = actionsReadActionResponses[keyof actionsReadActionResponses];

export type actionsUpdateActionData = {
    body: ActionItemUpdate;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/v1/actions/{action_id}';
};

export type actionsUpdateActionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsUpdateActionError = actionsUpdateActionErrors[keyof actionsUpdateActionErrors];

export type actionsUpdateActionResponses = {
    /**
     * Successful Response
     */
    200: ActionItemPublic;
};

export type actionsUpdateActionResponse = actionsUpdateActionResponses[keyof actionsUpdateActionResponses];

export type actionsReadActionSourceBriefingData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/v1/actions/{action_id}/source-briefing';
};

export type actionsReadActionSourceBriefingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsReadActionSourceBriefingError = actionsReadActionSourceBriefingErrors[keyof actionsReadActionSourceBriefingErrors];

export type actionsReadActionSourceBriefingResponses = {
    /**
     * Successful Response
     */
    200: AIDailyBriefingPublic;
};

export type actionsReadActionSourceBriefingResponse = actionsReadActionSourceBriefingResponses[keyof actionsReadActionSourceBriefingResponses];

export type actionsReadActionSourceWeeklyReviewData = {
    body?: never;
    path: {
        /**
         * Action Id
         */
        action_id: string;
    };
    query?: never;
    url: '/api/v1/actions/{action_id}/source-weekly-review';
};

export type actionsReadActionSourceWeeklyReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type actionsReadActionSourceWeeklyReviewError = actionsReadActionSourceWeeklyReviewErrors[keyof actionsReadActionSourceWeeklyReviewErrors];

export type actionsReadActionSourceWeeklyReviewResponses = {
    /**
     * Successful Response
     */
    200: AIWeeklyReviewPublic;
};

export type actionsReadActionSourceWeeklyReviewResponse = actionsReadActionSourceWeeklyReviewResponses[keyof actionsReadActionSourceWeeklyReviewResponses];

export type aiReadAiStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/status';
};

export type aiReadAiStatusResponses = {
    /**
     * Successful Response
     */
    200: AIStatusPublic;
};

export type aiReadAiStatusResponse = aiReadAiStatusResponses[keyof aiReadAiStatusResponses];

export type aiReadLatestDailyBriefingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Report Date
         */
        report_date?: string | null;
    };
    url: '/api/v1/ai/daily-briefing';
};

export type aiReadLatestDailyBriefingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiReadLatestDailyBriefingError = aiReadLatestDailyBriefingErrors[keyof aiReadLatestDailyBriefingErrors];

export type aiReadLatestDailyBriefingResponses = {
    /**
     * Response Ai-Read Latest Daily Briefing
     *
     * Successful Response
     */
    200: AIDailyBriefingPublic | null;
};

export type aiReadLatestDailyBriefingResponse = aiReadLatestDailyBriefingResponses[keyof aiReadLatestDailyBriefingResponses];

export type aiCreateDailyBriefingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Report Date
         */
        report_date?: string | null;
    };
    url: '/api/v1/ai/daily-briefing';
};

export type aiCreateDailyBriefingErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiCreateDailyBriefingError = aiCreateDailyBriefingErrors[keyof aiCreateDailyBriefingErrors];

export type aiCreateDailyBriefingResponses = {
    /**
     * Successful Response
     */
    200: AIDailyBriefingPublic;
};

export type aiCreateDailyBriefingResponse = aiCreateDailyBriefingResponses[keyof aiCreateDailyBriefingResponses];

export type aiReadDailyBriefingHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Report Date
         */
        report_date?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/ai/daily-briefings';
};

export type aiReadDailyBriefingHistoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiReadDailyBriefingHistoryError = aiReadDailyBriefingHistoryErrors[keyof aiReadDailyBriefingHistoryErrors];

export type aiReadDailyBriefingHistoryResponses = {
    /**
     * Successful Response
     */
    200: AIDailyBriefingsPublic;
};

export type aiReadDailyBriefingHistoryResponse = aiReadDailyBriefingHistoryResponses[keyof aiReadDailyBriefingHistoryResponses];

export type aiReadDailyBriefingAutomationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/automation/daily-briefing';
};

export type aiReadDailyBriefingAutomationResponses = {
    /**
     * Successful Response
     */
    200: AIDailyAutomationPublic;
};

export type aiReadDailyBriefingAutomationResponse = aiReadDailyBriefingAutomationResponses[keyof aiReadDailyBriefingAutomationResponses];

export type aiUpdateDailyBriefingAutomationData = {
    body: AIDailyAutomationUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/ai/automation/daily-briefing';
};

export type aiUpdateDailyBriefingAutomationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiUpdateDailyBriefingAutomationError = aiUpdateDailyBriefingAutomationErrors[keyof aiUpdateDailyBriefingAutomationErrors];

export type aiUpdateDailyBriefingAutomationResponses = {
    /**
     * Successful Response
     */
    200: AIDailyAutomationPublic;
};

export type aiUpdateDailyBriefingAutomationResponse = aiUpdateDailyBriefingAutomationResponses[keyof aiUpdateDailyBriefingAutomationResponses];

export type aiRunDailyBriefingAutomationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/automation/daily-briefing/run';
};

export type aiRunDailyBriefingAutomationResponses = {
    /**
     * Successful Response
     */
    200: AIAutomationRunPublic;
};

export type aiRunDailyBriefingAutomationResponse = aiRunDailyBriefingAutomationResponses[keyof aiRunDailyBriefingAutomationResponses];

export type aiReadLatestWeeklyReviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * End Date
         */
        end_date?: string | null;
    };
    url: '/api/v1/ai/weekly-review';
};

export type aiReadLatestWeeklyReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiReadLatestWeeklyReviewError = aiReadLatestWeeklyReviewErrors[keyof aiReadLatestWeeklyReviewErrors];

export type aiReadLatestWeeklyReviewResponses = {
    /**
     * Response Ai-Read Latest Weekly Review
     *
     * Successful Response
     */
    200: AIWeeklyReviewPublic | null;
};

export type aiReadLatestWeeklyReviewResponse = aiReadLatestWeeklyReviewResponses[keyof aiReadLatestWeeklyReviewResponses];

export type aiCreateWeeklyReviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * End Date
         */
        end_date?: string | null;
    };
    url: '/api/v1/ai/weekly-review';
};

export type aiCreateWeeklyReviewErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiCreateWeeklyReviewError = aiCreateWeeklyReviewErrors[keyof aiCreateWeeklyReviewErrors];

export type aiCreateWeeklyReviewResponses = {
    /**
     * Successful Response
     */
    200: AIWeeklyReviewPublic;
};

export type aiCreateWeeklyReviewResponse = aiCreateWeeklyReviewResponses[keyof aiCreateWeeklyReviewResponses];

export type aiReadWeeklyReviewHistoryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * End Date
         */
        end_date?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/ai/weekly-reviews';
};

export type aiReadWeeklyReviewHistoryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type aiReadWeeklyReviewHistoryError = aiReadWeeklyReviewHistoryErrors[keyof aiReadWeeklyReviewHistoryErrors];

export type aiReadWeeklyReviewHistoryResponses = {
    /**
     * Successful Response
     */
    200: AIWeeklyReviewsPublic;
};

export type aiReadWeeklyReviewHistoryResponse = aiReadWeeklyReviewHistoryResponses[keyof aiReadWeeklyReviewHistoryResponses];

export type productsReadProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/products/';
};

export type productsReadProductsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsReadProductsError = productsReadProductsErrors[keyof productsReadProductsErrors];

export type productsReadProductsResponses = {
    /**
     * Successful Response
     */
    200: ProductsPublic;
};

export type productsReadProductsResponse = productsReadProductsResponses[keyof productsReadProductsResponses];

export type productsCreateProductData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/api/v1/products/';
};

export type productsCreateProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsCreateProductError = productsCreateProductErrors[keyof productsCreateProductErrors];

export type productsCreateProductResponses = {
    /**
     * Successful Response
     */
    201: ProductPublic;
};

export type productsCreateProductResponse = productsCreateProductResponses[keyof productsCreateProductResponses];

export type productsDeleteProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsDeleteProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsDeleteProductError = productsDeleteProductErrors[keyof productsDeleteProductErrors];

export type productsDeleteProductResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type productsDeleteProductResponse = productsDeleteProductResponses[keyof productsDeleteProductResponses];

export type productsReadProductData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsReadProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsReadProductError = productsReadProductErrors[keyof productsReadProductErrors];

export type productsReadProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type productsReadProductResponse = productsReadProductResponses[keyof productsReadProductResponses];

export type productsUpdateProductData = {
    body: ProductUpdate;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type productsUpdateProductErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type productsUpdateProductError = productsUpdateProductErrors[keyof productsUpdateProductErrors];

export type productsUpdateProductResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type productsUpdateProductResponse = productsUpdateProductResponses[keyof productsUpdateProductResponses];

export type salesReadSalesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/sales/';
};

export type salesReadSalesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type salesReadSalesError = salesReadSalesErrors[keyof salesReadSalesErrors];

export type salesReadSalesResponses = {
    /**
     * Successful Response
     */
    200: SalesPublic;
};

export type salesReadSalesResponse = salesReadSalesResponses[keyof salesReadSalesResponses];

export type salesCreateSaleData = {
    body: SaleCreate;
    path?: never;
    query?: never;
    url: '/api/v1/sales/';
};

export type salesCreateSaleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type salesCreateSaleError = salesCreateSaleErrors[keyof salesCreateSaleErrors];

export type salesCreateSaleResponses = {
    /**
     * Successful Response
     */
    201: SalePublic;
};

export type salesCreateSaleResponse = salesCreateSaleResponses[keyof salesCreateSaleResponses];

export type salesReadSaleData = {
    body?: never;
    path: {
        /**
         * Sale Id
         */
        sale_id: string;
    };
    query?: never;
    url: '/api/v1/sales/{sale_id}';
};

export type salesReadSaleErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type salesReadSaleError = salesReadSaleErrors[keyof salesReadSaleErrors];

export type salesReadSaleResponses = {
    /**
     * Successful Response
     */
    200: SalePublic;
};

export type salesReadSaleResponse = salesReadSaleResponses[keyof salesReadSaleResponses];

export type inventoryReadInventoryMovementsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Product Id
         */
        product_id?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/inventory/movements/';
};

export type inventoryReadInventoryMovementsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type inventoryReadInventoryMovementsError = inventoryReadInventoryMovementsErrors[keyof inventoryReadInventoryMovementsErrors];

export type inventoryReadInventoryMovementsResponses = {
    /**
     * Successful Response
     */
    200: InventoryMovementsPublic;
};

export type inventoryReadInventoryMovementsResponse = inventoryReadInventoryMovementsResponses[keyof inventoryReadInventoryMovementsResponses];

export type inventoryCreateInventoryMovementData = {
    body: InventoryMovementCreate;
    path?: never;
    query?: never;
    url: '/api/v1/inventory/movements/';
};

export type inventoryCreateInventoryMovementErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type inventoryCreateInventoryMovementError = inventoryCreateInventoryMovementErrors[keyof inventoryCreateInventoryMovementErrors];

export type inventoryCreateInventoryMovementResponses = {
    /**
     * Successful Response
     */
    201: InventoryMovementPublic;
};

export type inventoryCreateInventoryMovementResponse = inventoryCreateInventoryMovementResponses[keyof inventoryCreateInventoryMovementResponses];

export type inventoryReadInventoryBalancesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/inventory/balances/';
};

export type inventoryReadInventoryBalancesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type inventoryReadInventoryBalancesError = inventoryReadInventoryBalancesErrors[keyof inventoryReadInventoryBalancesErrors];

export type inventoryReadInventoryBalancesResponses = {
    /**
     * Successful Response
     */
    200: InventoryBalancesPublic;
};

export type inventoryReadInventoryBalancesResponse = inventoryReadInventoryBalancesResponses[keyof inventoryReadInventoryBalancesResponses];

export type inventoryReadLowStockProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/inventory/low-stock/';
};

export type inventoryReadLowStockProductsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type inventoryReadLowStockProductsError = inventoryReadLowStockProductsErrors[keyof inventoryReadLowStockProductsErrors];

export type inventoryReadLowStockProductsResponses = {
    /**
     * Successful Response
     */
    200: InventoryBalancesPublic;
};

export type inventoryReadLowStockProductsResponse = inventoryReadLowStockProductsResponses[keyof inventoryReadLowStockProductsResponses];

export type inventoryReadInventoryBalanceData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/inventory/balances/{product_id}';
};

export type inventoryReadInventoryBalanceErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type inventoryReadInventoryBalanceError = inventoryReadInventoryBalanceErrors[keyof inventoryReadInventoryBalanceErrors];

export type inventoryReadInventoryBalanceResponses = {
    /**
     * Successful Response
     */
    200: InventoryBalancePublic;
};

export type inventoryReadInventoryBalanceResponse = inventoryReadInventoryBalanceResponses[keyof inventoryReadInventoryBalanceResponses];

export type dashboardReadDashboardSummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Report Date
         */
        report_date?: string | null;
        /**
         * Top Limit
         */
        top_limit?: number;
        /**
         * Low Stock Limit
         */
        low_stock_limit?: number;
    };
    url: '/api/v1/dashboard/summary/';
};

export type dashboardReadDashboardSummaryErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dashboardReadDashboardSummaryError = dashboardReadDashboardSummaryErrors[keyof dashboardReadDashboardSummaryErrors];

export type dashboardReadDashboardSummaryResponses = {
    /**
     * Successful Response
     */
    200: DashboardSummaryPublic;
};

export type dashboardReadDashboardSummaryResponse = dashboardReadDashboardSummaryResponses[keyof dashboardReadDashboardSummaryResponses];

export type dashboardReadDashboardTrendsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * End Date
         */
        end_date?: string | null;
        days?: TrendDays;
    };
    url: '/api/v1/dashboard/trends/';
};

export type dashboardReadDashboardTrendsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type dashboardReadDashboardTrendsError = dashboardReadDashboardTrendsErrors[keyof dashboardReadDashboardTrendsErrors];

export type dashboardReadDashboardTrendsResponses = {
    /**
     * Successful Response
     */
    200: DashboardTrendsPublic;
};

export type dashboardReadDashboardTrendsResponse = dashboardReadDashboardTrendsResponses[keyof dashboardReadDashboardTrendsResponses];

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
